project_id = "zygzuoodjenpbvfgfika"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[functions.generate-json-export]
verify_jwt = false

[functions.create-user]
verify_jwt = true

[functions.manual-json-export]
verify_jwt = true

[functions.create-admin-user]
verify_jwt = false

[functions.delete-client]
verify_jwt = true

[functions.delete-user]
verify_jwt = true

[functions.generate-invite-link]
verify_jwt = false

[functions.update-client-id]
verify_jwt = true

[functions.sync-to-gcp]
verify_jwt = false

[functions.scheduled-backup]
verify_jwt = false

[functions.crud-backup]
verify_jwt = false

[functions.import-eco-movement]
verify_jwt = false
